import { StyleSheet } from "react-native";

const menuStyleSheet = StyleSheet.create({
  menu: {
    paddingLeft: 0,
    backgroundColor: "#292525",
    boxShadow: "0px 4px 3px 1px #F2FF43",
    outlineStyle: "solid",
    outlineColor: "#F2FF43",
    display: "flex",
  },
  menu_button_big: {
    flexDirection: "row",
    display: "flex",
    marginLeft: 20,
    justifyContent: "flex-start",
    columnGap: "55px",
    outlineColor: "#F2FF43",
    width: 541,
    height: 121,
    paddingLeft: 0,
    backgroundColor: "#292525",
    boxShadow: "0px 4px 3px 1px #F2FF43",
    outlineStyle: "solid",
    borderRadius: 10,
  },
  menu_text_big: {
    color: "#FFE365",
    fontFamily: "'Raleway', 'Arial', 'sans-serif'",
    verticalAlign: "middle",
    marginLeft: "40%",
    position: "absolute",
    textAlign: "center",
    paddingTop: "6%",
    fontSize: 48,
  },
  menu_button_small: {
    flexDirection: "row",
    display: "flex",
    marginLeft: 20,
    justifyContent: "flex-start",
    columnGap: "55px",
    outlineColor: "#F2FF43",
    width: 242,
    height: 67,
    paddingLeft: 0,
    backgroundColor: "#292525",
    boxShadow: "0px 4px 3px 1px #F2FF43",
    outlineStyle: "solid",
    borderRadius: 10,
  },
  menu_text_small: {
    color: "#FFE365",
    fontFamily: "'Raleway', 'Arial', 'sans-serif'",
    textAlignVertical: "center",
    position: "absolute",
    textAlign: "center",
    paddingTop: "6%",
    fontSize: 24,
    marginLeft: "40%",
    marginTop: "3%",
  },
  main_menu: {
    flexDirection: "row",
    display: "flex",
    marginLeft: 0,
    justifyContent: "space-between",
    columnGap: "37px",
    outlineColor: "#F2FF43",
  },
  button_side_image: {
    height: 100,
    width: 100,
    marginLeft: 140,
    marginTop: 15,
    verticalAlign: "middle",
  },
});

export default menuStyleSheet;
